nome=input("Digite um Funcionário: ")
empresa=input("Digite a Instituição: ")
qtde_funcionarios=int(input("Digite a qtde de funcionários: "))
mediaMensalidade=float(input("Digite a média da mensalidade: "))
print(nome + "Trabalha na Empresa" +empresa)
print("Possui:",qtde_funcionarios, "funcionarios.")
print("A média da mensalidade e de:" +str(mediaMensalidade))
print("========Verifique os tipos de dados abaixo:")
print("O tipo de dado da variável [nome] é: ",type(nome))
print("O tipo de dado da variável [empresa] é:",type(empresa))
print("O tipo de dado da variável [qtde_funcionarios é:",type(qtde_funcionarios))
print("O tipo de dado da variável [mediaMensalidade é:",type(mediaMensalidade))